/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author whoami
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        CadastrosBarComp = new javax.swing.JMenu();
        MenuAddHospedes = new javax.swing.JMenu();
        BtnCadastrarHospede = new javax.swing.JMenuItem();
        BtnConsultarHospede = new javax.swing.JMenuItem();
        MenuAddQuartos = new javax.swing.JMenu();
        BtnCadastrarQuarto = new javax.swing.JMenuItem();
        BtnConsultarQuarto = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraMenu.setBackground([238,238,238]);

        CadastrosBarComp.setForeground(java.awt.Color.black);
        CadastrosBarComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        CadastrosBarComp.setText("Cadastros   |");
        CadastrosBarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        MenuAddHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_hospede.png"))); // NOI18N
        MenuAddHospedes.setText("Hóspedes");

        BtnCadastrarHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        BtnCadastrarHospede.setText("Cadastrar");
        MenuAddHospedes.add(BtnCadastrarHospede);

        BtnConsultarHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_man_usersearch_thesearch_theclient_2356_1.png"))); // NOI18N
        BtnConsultarHospede.setText("Consultar");
        BtnConsultarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarHospedeActionPerformed(evt);
            }
        });
        MenuAddHospedes.add(BtnConsultarHospede);

        CadastrosBarComp.add(MenuAddHospedes);

        MenuAddQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        MenuAddQuartos.setText("Quartos");

        BtnCadastrarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        BtnCadastrarQuarto.setText("Adicionar");
        MenuAddQuartos.add(BtnCadastrarQuarto);

        BtnConsultarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        BtnConsultarQuarto.setText("Consultar");
        BtnConsultarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarQuartoActionPerformed(evt);
            }
        });
        MenuAddQuartos.add(BtnConsultarQuarto);

        CadastrosBarComp.add(MenuAddQuartos);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_funcionario.png"))); // NOI18N
        jMenu8.setText("Funcionários");
        CadastrosBarComp.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_fornecedor.png"))); // NOI18N
        jMenu9.setText("Fornecedores");
        CadastrosBarComp.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_produtos.png"))); // NOI18N
        jMenu10.setText("Produtos");
        CadastrosBarComp.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_servicos.png"))); // NOI18N
        jMenu11.setText("Serviços");
        CadastrosBarComp.add(jMenu11);

        BarraMenu.add(CadastrosBarComp);

        jMenu2.setForeground(java.awt.Color.black);
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendario.png"))); // NOI18N
        jMenu2.setText("Reservas   |");
        BarraMenu.add(jMenu2);

        jMenu3.setForeground(java.awt.Color.black);
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        jMenu3.setText("Vendas");
        BarraMenu.add(jMenu3);

        jMenu4.setForeground(java.awt.Color.black);
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        jMenu4.setText("Financeiro   |");
        BarraMenu.add(jMenu4);

        jMenu5.setForeground(java.awt.Color.black);
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorios.png"))); // NOI18N
        jMenu5.setText("Relatórios   |");
        BarraMenu.add(jMenu5);

        jMenu6.setForeground(java.awt.Color.black);
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seguranca.png"))); // NOI18N
        jMenu6.setText("Segurança   |");
        BarraMenu.add(jMenu6);

        jMenu7.setForeground(java.awt.Color.black);
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas.png"))); // NOI18N
        jMenu7.setText("Ferramentas   |");
        BarraMenu.add(jMenu7);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        jMenu1.setText("Sair");
        BarraMenu.add(jMenu1);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConsultarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarHospedeActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsultarHospedeActionPerformed

    private void BtnConsultarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarQuartoActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsultarQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem BtnCadastrarHospede;
    private javax.swing.JMenuItem BtnCadastrarQuarto;
    private javax.swing.JMenuItem BtnConsultarHospede;
    private javax.swing.JMenuItem BtnConsultarQuarto;
    private javax.swing.JMenu CadastrosBarComp;
    private javax.swing.JMenu MenuAddHospedes;
    private javax.swing.JMenu MenuAddQuartos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    // End of variables declaration//GEN-END:variables
}
