/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author whoami
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        CadastrosBarComp = new javax.swing.JMenu();
        MenuAddHospedes = new javax.swing.JMenu();
        BtnCadastrarHospede = new javax.swing.JMenuItem();
        BtnConsultarHospede = new javax.swing.JMenuItem();
        MenuAddQuartos = new javax.swing.JMenu();
        BtnCadastrarQuarto = new javax.swing.JMenuItem();
        BtnConsultarQuarto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraMenu.setBackground(java.awt.Color.black);

        CadastrosBarComp.setForeground(java.awt.Color.white);
        CadastrosBarComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        CadastrosBarComp.setText("Cadastros   |");

        MenuAddHospedes.setText("Hóspedes");

        BtnCadastrarHospede.setText("Cadastrar");
        MenuAddHospedes.add(BtnCadastrarHospede);

        BtnConsultarHospede.setText("Consultar");
        BtnConsultarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarHospedeActionPerformed(evt);
            }
        });
        MenuAddHospedes.add(BtnConsultarHospede);

        CadastrosBarComp.add(MenuAddHospedes);

        MenuAddQuartos.setText("Quartos");

        BtnCadastrarQuarto.setText("Adicionar");
        MenuAddQuartos.add(BtnCadastrarQuarto);

        BtnConsultarQuarto.setText("Consultar");
        BtnConsultarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarQuartoActionPerformed(evt);
            }
        });
        MenuAddQuartos.add(BtnConsultarQuarto);

        CadastrosBarComp.add(MenuAddQuartos);

        BarraMenu.add(CadastrosBarComp);

        jMenu2.setForeground(java.awt.Color.white);
        jMenu2.setText("Reservas   |");
        BarraMenu.add(jMenu2);

        jMenu3.setForeground(java.awt.Color.white);
        jMenu3.setText("Consumos  |");
        BarraMenu.add(jMenu3);

        jMenu4.setForeground(java.awt.Color.white);
        jMenu4.setText("Financeiro   |");
        BarraMenu.add(jMenu4);

        jMenu5.setForeground(java.awt.Color.white);
        jMenu5.setText("Relatórios   |");
        BarraMenu.add(jMenu5);

        jMenu6.setForeground(java.awt.Color.white);
        jMenu6.setText("Segurança   |");
        BarraMenu.add(jMenu6);

        jMenu7.setForeground(java.awt.Color.white);
        jMenu7.setText("Ferramentas");
        BarraMenu.add(jMenu7);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConsultarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarHospedeActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsultarHospedeActionPerformed

    private void BtnConsultarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarQuartoActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsultarQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem BtnCadastrarHospede;
    private javax.swing.JMenuItem BtnCadastrarQuarto;
    private javax.swing.JMenuItem BtnConsultarHospede;
    private javax.swing.JMenuItem BtnConsultarQuarto;
    private javax.swing.JMenu CadastrosBarComp;
    private javax.swing.JMenu MenuAddHospedes;
    private javax.swing.JMenu MenuAddQuartos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    // End of variables declaration//GEN-END:variables
}
